HeroBanner Added in Both Mobile and Desktop
victorchrollo14/mernEcommerce pull request #31
Opened 2023-08-10 12:39 UTC by Monilprajapati

Created Hero Banner for both Mobile and desktop devices

2023-08-10 16:17 UTC, victorchrollo14 commented
@Monilprajapati .Looks good on mobile, try and add a clamp for fontsize for that text in hero section so that increases till 600px, Then break it at sm: to look like desktop design.

2023-08-10 16:29 UTC, victorchrollo14 requested changes
just fix these, that's all.

2023-08-10 16:29 UTC, victorchrollo14 commented on client/src/pages/home/Home.jsx
> +import Footer from "../../components/Footer";
remove this line since, it's already imported and causing an error.

2023-08-11 17:36 UTC, Monilprajapati commented on client/src/pages/home/Home.jsx
> +import Footer from "../../components/Footer";
Okkkay will fix it

2023-08-21 09:07 UTC, victorchrollo14 approved these changes
looks good.

2023-08-21 09:10 UTC, merged