#59 Product slider ADDED
victorchrollo14/mernEcommerce pull request #63
Opened 2023-09-22 17:08 UTC by Sky-De

## This PR closes  issue #59

## What did i do ?

1. I've decided connect to server with my own mongoDb url but as there was no data or images  i just created mock data with images in code and implemented Carousel ( responsive ) using that, now it is commented for test cases , if you want you can remove that

2. I've added styles to index.css to customizing react-responsive-carousel  

## Show case gif of final result - It takes a few second to load gifs

**Desktop**
![sliderShowCaseD-min](https://github.com/victorchrollo14/mernEcommerce/assets/79264045/ce7d8a79-bf25-46bc-afe1-0282b07bc6ea)

**Mobile**
![sliderShowCaseM-min](https://github.com/victorchrollo14/mernEcommerce/assets/79264045/0f172e41-f515-44e9-ba77-f9803a5dbb48)

if you got any question feel free to ask, otherwise merge SECOND COMMIT
thanks

2023-09-22 17:14 UTC, Sky-De commented
I don't have access to take a look why deployment has failed, please provide screen shot of corresponding deployment error or if you can just fix it by yourself, let me know 
Thanks

2023-09-23 03:52 UTC, victorchrollo14 commented
> 1. I've decided connect to server with my own mongoDb url but as there was no data or images  i just created mock data with images in code and implemented Carousel ( responsive ) using that, now it is commented for test cases , if you want you can remove that

I have given it in the readme, you should run this to insert data into mongodb
if you have specified the mongodb uri in .env file, it would work fine.
``` 
cd server/src/utils/

node insertData.js
```

2023-09-23 04:05 UTC, victorchrollo14 commented
> I don't have access to take a look why deployment has failed, please provide screen shot of corresponding deployment error or if you can just fix it by yourself, let me know Thanks

seems like you forgot to add package.json file to staging before making your commit as a result it was not installed.

![image](https://github.com/victorchrollo14/mernEcommerce/assets/89346667/35275d88-407e-4a36-8b80-77776c8842ed)

2023-09-23 04:44 UTC, victorchrollo14 commented
* Change those next and previous buttons to something similar to the design in figma
* Place those smaller images below the large image towards bottom left and increase it's size a little bit. it looks too small.
* You can look into the design for reference.
https://www.figma.com/file/figjD5PRyaAJ5ffTFVOMDN/Ecommerce-Site-Mern?type=design&node-id=38-383&mode=design&t=12x3SvJUpFQNYNcn-0

![image](https://github.com/victorchrollo14/mernEcommerce/assets/89346667/1998d38c-bdd2-48c2-9bd1-4e89aed7b55f)

2023-09-23 04:47 UTC, victorchrollo14 requested changes

2023-09-23 04:47 UTC, victorchrollo14 commented on client/src/pages/product/product.jsx
> +  //   ],
Remove this when you make the next changes.

2023-09-23 04:49 UTC, victorchrollo14 commented
@Sky-De The slider works fine.Good work. 
Just make the above changes, then we can merge it up.

2023-09-23 11:52 UTC, Sky-De commented
@victorchrollo14 ok i'll fix them, however i took a look at your figma design and there was no match with screenshot which you provided before

![1111](https://github.com/victorchrollo14/mernEcommerce/assets/79264045/8aff7ff6-d5e6-42d2-ac36-21ecbfe45b3d)

do you want design be match with this screen shot ?

2023-09-23 12:29 UTC, victorchrollo14 commented
> @victorchrollo14 ok i'll fix them, however i took a look at your figma design and there was no match with screenshot which you provided before
> do you want design be match with this screen shot ?

The screenshot is how the page looks with changes you made. Just make it as it looks like in the figma design

2023-09-23 16:17 UTC, Sky-De commented
@victorchrollo14 it is done now, there is just a little change in arrow btns because with color of design (#000) there will hidden in images with white bg, also black for these arrows wont work because in other images with dark bg it will be hard to see
this screen shot is show case of issue :


![asdasd](https://github.com/victorchrollo14/mernEcommerce/assets/79264045/f9a3f7f1-6b05-4eac-b420-39c45b2343bc)


##  Gif of final result
as a result of bg problem which mentioned before, i had to change arrow styles a bit , then this is the final UI :

![chrome-capture-2023-8-23-min (1)](https://github.com/victorchrollo14/mernEcommerce/assets/79264045/968a45ad-ea9c-4f1f-bb55-cbf8e37f6736)

If it works for you let me know to make commit of these changes
thanks

2023-09-24 06:18 UTC, victorchrollo14 commented
Ok That looks fine. Can you remove the extra white space to the right of the image and keep it like below. 


![Product Page](https://github.com/victorchrollo14/mernEcommerce/assets/89346667/126652d1-c52c-4edc-9fc0-82c8f4164e40)

2023-09-24 13:50 UTC, Sky-De commented
@victorchrollo14 i reduced amount of white space and it is better now, if i want to make it exactly look like your design i have to change rightSection styles  which is totally other issue

## Gif

![chrome-capture-2023-8-24-min](https://github.com/victorchrollo14/mernEcommerce/assets/79264045/cdcd9975-180d-48dc-a9a8-9af18a457dbe)


## consider
i made a commit and it is ready to use
last commit
thanks

2023-09-25 10:47 UTC, victorchrollo14 commented
> @victorchrollo14 i reduced amount of white space and it is better now, if i want to make it exactly look like your design i have to change rightSection styles which is totally other issue

You don't have to change the entire thing, I tried it, it's a simple fix.
max-w-[600px] add this to the div with className="left_section"
then remove lg:w-[70%] from Carousel  Component.
it would look like this when you make the changes.


![image](https://github.com/victorchrollo14/mernEcommerce/assets/89346667/d0bfeed3-9695-4347-8cbb-60f3efa1565b)

2023-09-25 10:55 UTC, victorchrollo14 approved these changes

2023-09-25 10:56 UTC, victorchrollo14 commented
@Sky-De Good work. I was able to edit that directly, So I'm merging it up.

2023-09-25 10:56 UTC, merged

2024-05-16 07:47 UTC, Sky-De commented
@victorchrollo14 Hi, may I ask you a favor? I'd appreciate it if you could take a look at my [Portfolio ](https://skyde-portfolio.netlify.app/)and other projects. Please let me know what you think about them, and if you like them, please give them a STAR. All public projects can be found in the PROJECTS section of my portfolio. Within that section, you can find live demo links as well as repository links related to each project. And if you like my project please mention other colleagues of these projects here to check my [Portfolio ](https://skyde-portfolio.netlify.app/), thanks thanks

2024-05-16 15:16 UTC, victorchrollo14 commented
your portfolio looks cool. what problem are you facing right now.
I too am a student just learning and building stuff.
just hit me up on twitter, we could have a chat.

2024-05-16 15:20 UTC, Sky-De commented
> your portfolio looks cool. what problem are you facing right now. I too am a student just learning and building stuff. just hit me up on twitter, we could have a chat.

Thanks for looking at it, i don't have any problem with that, i just asked people who i contribute with to take a look and give my projects start, take a look at book sharing too, if you like give it star too and leave a feedback in that project itself
Thanks

2024-05-16 16:13 UTC, victorchrollo14 commented
> > your portfolio looks cool. what problem are you facing right now. I too am a student just learning and building stuff. just hit me up on twitter, we could have a chat.
> 
> Thanks for looking at it, i don't have any problem with that, i just asked people who i contribute with to take a look and give my projects start, take a look at book sharing too, if you like give it star too and leave a feedback in that project itself
> Thanks

Yeah sure.